import * as THREE from 'three';

export const estruturasPorAnimal = {
  "Cachorro": {
    ossea: [
      { nome: "Costela", position: new THREE.Vector3(0.29, 0.01, -0.00) },
      { nome: "Vértebra Caudal", position: new THREE.Vector3(0.02, -0.20, -1.60) },
      { nome: "Crânio", position: new THREE.Vector3(0.18, 0.79, 1.18) },
      { nome: "Mandíbula", position: new THREE.Vector3(0.13, 0.48, 1.42) },
      { nome: "Escápula", position: new THREE.Vector3(0.23, 0.17, 0.47) },
      { nome: "Úmero", position: new THREE.Vector3(0.36, -0.28, 0.64) },
      { nome: "Rádio", position: new THREE.Vector3(0.31, -0.81, 0.40) },
      { nome: "Ulna", position: new THREE.Vector3(0.35, -0.82, 0.35) },
      { nome: "Carpo", position: new THREE.Vector3(0.30, -1.28, 0.42) },
      { nome: "MetaCarpo", position: new THREE.Vector3(0.38, -1.40, 0.45) },
      { nome: "Falange", position: new THREE.Vector3(0.37, -1.47, 0.53) },
      { nome: "Vértebra cervical", position: new THREE.Vector3(0.04, 0.47, 0.92) },
      { nome: "Vértebra Torácica", position: new THREE.Vector3(0.02, 0.34, 0.20) },
      { nome: "Vértebra Lombar", position: new THREE.Vector3(0.01, 0.26, -0.59) },
      { nome: "Tíbia", position: new THREE.Vector3(0.34, -0.74, -1.29) },
      { nome: "Ílio", position: new THREE.Vector3(0.13, 0.19, -0.99) },
      { nome: "Ísquio", position: new THREE.Vector3(0.18, 0.03, -1.20) },
      { nome: "Sacro", position: new THREE.Vector3(0.02, 0.24, -1.11) },
      { nome: "Fêmur", position: new THREE.Vector3(0.32, -0.26, -1.21) },
      { nome: "Patela", position: new THREE.Vector3(0.38, -0.60, -1.16) },
      { nome: "Tarso", position: new THREE.Vector3(0.37, -1.05, -1.62) },
      { nome: "MetaTarso", position: new THREE.Vector3(0.36, -1.23, -1.59) },
    ],
    orgaosM: [
      { nome: "Coração" },
      { nome: "Aorta" },
      { nome: "Veia Cava" },
      { nome: "Pulmões" },
      { nome: "Traqueia" },
      { nome: "Diafragma" },
      { nome: "Fígado" },
      { nome: "Estômago" },
      { nome: "Intestino Delgado" },
      { nome: "Intestino Grosso" },
      { nome: "Pâncreas" },
      { nome: "Rins" },
      { nome: "Bexiga" },
      { nome: "Próstata" },
      { nome: "Cérebro" },
      { nome: "Medula Espinhal" },
  ],
  orgaosF: [
      { nome: "Coração" },
      { nome: "Aorta" },
      { nome: "Veia Cava" },
      { nome: "Pulmões" },
      { nome: "Traqueia" },
      { nome: "Diafragma" },
      { nome: "Fígado" },
      { nome: "Estômago" },
      { nome: "Intestino Delgado" },
      { nome: "Intestino Grosso" },
      { nome: "Pâncreas" },
      { nome: "Rins" },
      { nome: "Bexiga" },
      { nome: "Útero" },
      { nome: "Ovários" },
      { nome: "Cérebro" },
      { nome: "Medula Espinhal" },
  ],
    muscular: [
      { nome: "Tríceps Braquial", position: new THREE.Vector3() },
      { nome: "Deltóide", position: new THREE.Vector3() },
      { nome: "Bíceps Braquial", position: new THREE.Vector3() },
      { nome: "Braquiocefálico", position: new THREE.Vector3() },
      { nome: "Bíceps Femoral", position: new THREE.Vector3() },
      { nome: "Quadríceps Femoral", position: new THREE.Vector3() },
      { nome: "Gastrocnêmio", position: new THREE.Vector3() },
      { nome: "Glúteo Médio", position: new THREE.Vector3() },
      { nome: "Semitendinoso", position: new THREE.Vector3() },
      { nome: "Semimembranoso", position: new THREE.Vector3() },
      { nome: "Grande Dorsal", position: new THREE.Vector3() },
      { nome: "Trapézio", position: new THREE.Vector3() },
      { nome: "Serrátil Ventral", position: new THREE.Vector3() },
      { nome: "Oblíquo Externo do Abdômen", position: new THREE.Vector3() },
      { nome: "Reto Abdominal", position: new THREE.Vector3() },
      { nome: "Masseter", position: new THREE.Vector3() },
      { nome: "Esternomastóideo", position: new THREE.Vector3() },
      { nome: "Temporal", position: new THREE.Vector3() },
      { nome: "Digástrico", position: new THREE.Vector3() },
      { nome: "Esterno-hióideo", position: new THREE.Vector3() },
      { nome: "Esternocefálico", position: new THREE.Vector3() }
]
  },
  "Gato": {
    ossea: [
    ],
    orgaos: [],
    muscular: [],
    epiderme: []
  },
  "Vaca": {
    ossea: [
      { nome: "Costela", position: new THREE.Vector3(0.40, 0.51, -0.13) },
      { nome: "Vértebra Caudal", position: new THREE.Vector3(0.02, 0.76, -1.77) },
      { nome: "Crânio", position: new THREE.Vector3(0.15, 0.87, 1.62) },
      { nome: "Mandíbula", position: new THREE.Vector3(0.17, 0.56, 1.45) },
      { nome: "Escápula", position: new THREE.Vector3(0.24, 0.83, 0.34) },
      { nome: "Úmero", position: new THREE.Vector3(0.37, 0.27, 0.36) },
      { nome: "Rádio", position: new THREE.Vector3(0.39, -0.05, 0.33) },
      { nome: "Ulna", position: new THREE.Vector3(0.40, 0.10, 0.25) },
      { nome: "Carpo", position: new THREE.Vector3(0.37, -0.28, 0.34) },
      { nome: "MetaCarpo", position: new THREE.Vector3(0.31, -0.48, 0.31) },
      { nome: "Falanges", position: new THREE.Vector3(0.34, -0.82, 0.38) },
      { nome: "Vértebras cervicais", position: new THREE.Vector3(0.09, 0.75, 0.90) },
      { nome: "Vértebras torácicas", position: new THREE.Vector3(0.02, 0.95, -0.03) },
      { nome: "Vértebras lombares", position: new THREE.Vector3(0.02, 0.95, -0.54) },
      { nome: "Tíbia", position: new THREE.Vector3(0.32, 0.07, -0.99) },
      { nome: "Vértebras sacrais", position: new THREE.Vector3(0.03, 0.89, -1.12) },
      { nome: "Fêmur", position: new THREE.Vector3(0.32, 0.54, -1.07) },
      { nome: "Patela", position: new THREE.Vector3(0.39, 0.36, -0.87) },
      { nome: "Tarso", position: new THREE.Vector3(0.38, -0.13, -1.09) },
      { nome: "MetaTarso", position: new THREE.Vector3(0.37, -0.41, -1.08) }
    ],
    orgaosM: [
      { nome: "Rúmen", position: new THREE.Vector3()},
      { nome: "Retículo", position: new THREE.Vector3() },
      { nome: "Omaso", position: new THREE.Vector3() },
      { nome: "Abomaso", position: new THREE.Vector3() },
      { nome: "Intestino delgado",  position: new THREE.Vector3() },
      { nome: "Intestino grosso", position: new THREE.Vector3() },
      { nome: "Fígado", position: new THREE.Vector3() },
      { nome: "Pâncreas", position: new THREE.Vector3() },
      { nome: "Pulmões", position: new THREE.Vector3() },
      { nome: "Coração", position: new THREE.Vector3() },
      { nome: "Rins", position: new THREE.Vector3() },
      { nome: "Bexiga", position: new THREE.Vector3() },
      { nome: "Testículos", position: new THREE.Vector3() },
],
    orgaosF: [
      { nome: "Rúmen", position: new THREE.Vector3() },
      { nome: "Retículo", position: new THREE.Vector3() },
      { nome: "Omaso", position: new THREE.Vector3() },
      { nome: "Abomaso", position: new THREE.Vector3() },
      { nome: "Intestino delgado", position: new THREE.Vector3() },
      { nome: "Intestino grosso", position: new THREE.Vector3() },
      { nome: "Fígado", position: new THREE.Vector3() },
      { nome: "Pâncreas", position: new THREE.Vector3() },
      { nome: "Pulmões", position: new THREE.Vector3() },
      { nome: "Coração", position: new THREE.Vector3() },
      { nome: "Rins", position: new THREE.Vector3() },
      { nome: "Bexiga", position: new THREE.Vector3() },
      { nome: "Útero", position: new THREE.Vector3() },
      { nome: "Ovários", position: new THREE.Vector3() },
      { nome: "Glândula mamária", position: new THREE.Vector3() },
],
    musculos: [
      { nome: "Tríceps Braquial", position: new THREE.Vector3() },
      { nome: "Deltóide", position: new THREE.Vector3() },
      { nome: "Braquiocefálico", position: new THREE.Vector3() },
      { nome: "Quadríceps Femoral", position: new THREE.Vector3() },
      { nome: "Gastrocnêmio", position: new THREE.Vector3() },
      { nome: "Glúteo Médio", position: new THREE.Vector3() },
      { nome: "Bíceps Femoral", position: new THREE.Vector3() },
      { nome: "Semitendinoso", position: new THREE.Vector3() },
      { nome: "Semimembranoso", position: new THREE.Vector3() },
      { nome: "Grande Dorsal", position: new THREE.Vector3() },
      { nome: "Serrátil Ventral", position: new THREE.Vector3() },
      { nome: "Oblíquo Externo do Abdômen", position: new THREE.Vector3() },
      { nome: "Reto Abdominal", position: new THREE.Vector3() },
      { nome: "Masseter", position: new THREE.Vector3() },
      { nome: "Temporal", position: new THREE.Vector3() },
      { nome: "Esternomandibular", position: new THREE.Vector3() },
      { nome: "Trapézio Cervical", position: new THREE.Vector3() },
      { nome: "Braquiocefálico Cervical", position: new THREE.Vector3() },
      { nome: "Esternocefálico", position: new THREE.Vector3() }
  ]
  },
  "Cavalo": {
    ossea: [
      { nome: "Costela", position: new THREE.Vector3(0.43, 0.20, -0.14) },
      { nome: "Vértebra Caudal", position: new THREE.Vector3(0.03, 0.53, -1.73) },
      { nome: "Crânio", position: new THREE.Vector3(0.12, 1.31, 1.52) },
      { nome: "Mandíbula", position: new THREE.Vector3(0.08, 0.84, 1.67) },
      { nome: "Escápula", position: new THREE.Vector3(0.20, 0.58, 0.32) },
      { nome: "Úmero", position: new THREE.Vector3(0.35, 0.08, 0.62) },
      { nome: "Rádio", position: new THREE.Vector3(0.30, -0.42, 0.42) },
      { nome: "Ulna", position: new THREE.Vector3(0.28, -0.54, 0.48) },
      { nome: "Carpo", position: new THREE.Vector3(0.28, -0.86, 0.47) },
      { nome: "MetaCarpo", position: new THREE.Vector3(0.23, -1.10, 0.43) },
      { nome: "Falanges", position: new THREE.Vector3(0.24, -1.36, 0.51) },
      { nome: "Vértebras cervicais", position: new THREE.Vector3(0.03, 0.88, 0.81) },
      { nome: "Vértebras torácicas", position: new THREE.Vector3(0.02, 0.64, -0.09) },
      { nome: "Vértebras lombares", position: new THREE.Vector3(0.01, 0.73, -0.81) },
      { nome: "Pelve", position: new THREE.Vector3(0.23, 0.50, -1.16) },
      { nome: "Tíbia", position: new THREE.Vector3(0.24, -0.34, -1.35) },
      { nome: "Fíbula", position: new THREE.Vector3(0.27, -0.32, -1.42) },
      { nome: "Vértebras sacrais", position: new THREE.Vector3(0.02, 0.73, -1.21) },
      { nome: "Fêmur", position: new THREE.Vector3(0.27, 0.08, -1.30) },
      { nome: "Patela", position: new THREE.Vector3(0.32, -0.15, -1.24) },
      { nome: "Tarso", position: new THREE.Vector3(0.27, -0.73, -1.69) },
      { nome: "MetaTarso", position: new THREE.Vector3(0.22, -1.04, -1.72) },
      { nome: "Falanges", position: new THREE.Vector3(0.23, -1.34, -1.64) }
    ],
    orgaosM: [
      { nome: "Coração", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Pulmões", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Traqueia", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Diafragma", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Esôfago", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Estômago", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Fígado", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Pâncreas", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Baço", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Rins", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Bexiga", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Intestino Delgado", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Ceco", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Cólon", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Reto", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Testículos", position: new THREE.Vector3(0, 0, 0) }
  ],

    orgaosF: [
      { nome: "Coração", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Pulmões", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Traqueia", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Diafragma", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Esôfago", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Estômago", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Fígado", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Pâncreas", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Baço", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Rins", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Bexiga", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Intestino Delgado", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Ceco", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Cólon", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Reto", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Ovários", position: new THREE.Vector3(0, 0, 0) },
      { nome: "Útero", position: new THREE.Vector3(0, 0, 0) }
  ],
    muscular: [
    { nome: "Tríceps Braquial", position: new THREE.Vector3() },
    { nome: "Bíceps Braquial", position: new THREE.Vector3() },
    { nome: "Braquiocefálico", position: new THREE.Vector3() },
    { nome: "Deltóide", position: new THREE.Vector3() },
    { nome: "Extensor Carpo Radial", position: new THREE.Vector3() },
    { nome: "Glúteo Médio", position: new THREE.Vector3() },
    { nome: "Glúteo Superficial", position: new THREE.Vector3() },
    { nome: "Bíceps Femoral", position: new THREE.Vector3() },
    { nome: "Semimembranoso", position: new THREE.Vector3() },
    { nome: "Semitendinoso", position: new THREE.Vector3() },
    { nome: "Quadríceps Femoral", position: new THREE.Vector3() },
    { nome: "Gastrocnêmio", position: new THREE.Vector3() },
    { nome: "Grande Dorsal", position: new THREE.Vector3() },
    { nome: "Serrátil Ventral", position: new THREE.Vector3() },
    { nome: "Longuíssimo do Dorso", position: new THREE.Vector3() },
    { nome: "Oblíquo Externo do Abdômen", position: new THREE.Vector3() },
    { nome: "Reto Abdominal", position: new THREE.Vector3() },
    { nome: "Esplênio", position: new THREE.Vector3() },
    { nome: "Braquiocefálico Cervical", position: new THREE.Vector3() },
    { nome: "Esternocefálico", position: new THREE.Vector3() },
    { nome: "Escaleno", position: new THREE.Vector3() },
    { nome: "Rombóide", position: new THREE.Vector3() }
]
  },
  "Peixe": {
    ossea: [
      { nome: "Órbita", position: new THREE.Vector3(-0.09, 0.02, 1.61) },
      { nome: "Opérculo", position: new THREE.Vector3(0.19, 0.05, 1.33) },
      { nome: "Mandíbula", position: new THREE.Vector3(0.08, -0.11, 1.76) }, 
      { nome: "Occipital", position: new THREE.Vector3(0.10, 0.29, 1.18) },
      { nome: "Frontal", position: new THREE.Vector3(0.11, 0.23, 1.40) },
      { nome: "Escápula", position: new THREE.Vector3(0.11, -0.21, 1.12) },
      { nome: "Clavícula", position: new THREE.Vector3(0.18, -0.00, 1.14) },
      { nome: "Costela", position: new THREE.Vector3(0.13, 0.04, 0.05) },
      { nome: "Vértebra", position: new THREE.Vector3(0.05, 0.24, -0.12) },
      { nome: "Nadadeira Peitoral", position: new THREE.Vector3(0.09, -0.25, 0.80) },
      { nome: "Nadadeira Dorsal", position: new THREE.Vector3(0.01, 0.59, 0.19) },
      { nome: "Nadadeira Ventral", position: new THREE.Vector3(0.15, -0.38, -0.12) },
      { nome: "Nadadeira Anal", position: new THREE.Vector3(0.02, -0.21, -0.94) },
      { nome: "Nadadeira caudal", position: new THREE.Vector3(0.04, 0.30, -1.73) },
    ],
    orgaosM: [
      { nome: "Coração", position: new THREE.Vector3() },
      { nome: "Brânquias", position: new THREE.Vector3() },
      { nome: "Fígado", position: new THREE.Vector3() },
      { nome: "Estômago", position: new THREE.Vector3() },
      { nome: "Intestino", position: new THREE.Vector3() },
      { nome: "Rins", position: new THREE.Vector3() },
      { nome: "Testículos", position: new THREE.Vector3() },
      { nome: "Encéfalo", position: new THREE.Vector3() },
      { nome: "Baço", position: new THREE.Vector3() },
      { nome: "Pâncreas", position: new THREE.Vector3() },
      { nome: "Bexiga Urinária", position: new THREE.Vector3() },
      { nome: "Bulbo Olfativo", position: new THREE.Vector3() }
  ],
    orgaosF: [
      { nome: "Coração", position: new THREE.Vector3() },
      { nome: "Brânquias", position: new THREE.Vector3() },
      { nome: "Fígado", position: new THREE.Vector3() },
      { nome: "Estômago", position: new THREE.Vector3() },
      { nome: "Intestino", position: new THREE.Vector3() },
      { nome: "Rins", position: new THREE.Vector3() },
      { nome: "Ovários", position: new THREE.Vector3() },
      { nome: "Encéfalo", position: new THREE.Vector3() },
      { nome: "Baço", position: new THREE.Vector3() },
      { nome: "Pâncreas", position: new THREE.Vector3() },
      { nome: "Bexiga Urinária", position: new THREE.Vector3() },
      { nome: "Bulbo Olfativo", position: new THREE.Vector3() }
  ],
    muscular: [
      { nome: "Musculatura Axial Segmentar", position: new THREE.Vector3() },
      { nome: "Músculos das Nadadeiras Pares", position: new THREE.Vector3() },
      { nome: "Músculos das Nadadeiras Dorsais", position: new THREE.Vector3() },
      { nome: "Músculos das Nadadeiras Anais", position: new THREE.Vector3() },
      { nome: "Músculos da Nadadeira Caudal", position: new THREE.Vector3() },
      { nome: "Adductor Mandibulae", position: new THREE.Vector3() },
      { nome: "Músculos Operculares", position: new THREE.Vector3() }
]
  },
  "Rato": {
    ossea: [
      { nome: "Costela", position: new THREE.Vector3(0.27, 0.14, 0.65) },
      { nome: "Vértebras Caudais", position: new THREE.Vector3(0.02, -0.13, -0.95) },
      { nome: "Crânio", position: new THREE.Vector3(0.17, 0.58, 1.46) },
      { nome: "Mandíbula", position: new THREE.Vector3(0.11, 0.26, 1.57) },
      { nome: "Escápula", position: new THREE.Vector3(0.20, 0.26, 0.87) },
      { nome: "Úmero", position: new THREE.Vector3(0.35, -0.10, 0.90) },
      { nome: "Rádio", position: new THREE.Vector3(0.42, -0.20, 0.76) },
      { nome: "Ulna", position: new THREE.Vector3(0.43, -0.28, 0.85) },
      { nome: "Carpo", position: new THREE.Vector3(0.46, -0.42, 0.93) },
      { nome: "MetaCarpo", position: new THREE.Vector3(0.48, -0.45, 0.99) },
      { nome: "Falanges", position: new THREE.Vector3(0.57, -0.47, 1.16) },
      { nome: "Vértebras cervicais", position: new THREE.Vector3(0.06, 0.34, 1.11) },
      { nome: "Vértebras torácicas", position: new THREE.Vector3(0.01, 0.39, 0.66) },
      { nome: "Vértebras lombares", position: new THREE.Vector3(0.02, 0.48, 0.15) },
      { nome: "Pelve", position: new THREE.Vector3(0.14, 0.14, -0.43) },
      { nome: "Púbis", position: new THREE.Vector3(0.22, -0.06, -0.61) },
      { nome: "Fêmur", position: new THREE.Vector3(0.24, -0.01, -0.43) },
      { nome: "Patela", position: new THREE.Vector3(0.37, 0.05, -0.25) },
      { nome: "Tíbia", position: new THREE.Vector3(0.36, -0.16, -0.43) },
      { nome: "Tarso", position: new THREE.Vector3(0.34, -0.40, -0.68) },
      { nome: "MetaTarso", position: new THREE.Vector3(0.37, -0.44, -0.57) },
      { nome: "Falanges", position: new THREE.Vector3(0.43, -0.47, -0.43) }],
    orgaosM: [
      { nome: "Estômago", position: new THREE.Vector3() },
      { nome: "Intestino Delgado", position: new THREE.Vector3() },
      { nome: "Intestino Grosso e Reto", position: new THREE.Vector3() },
      { nome: "Fígado", position: new THREE.Vector3() },
      { nome: "Pâncreas", position: new THREE.Vector3() },
      { nome: "Pulmões", position: new THREE.Vector3() },
      { nome: "Coração", position: new THREE.Vector3() },
      { nome: "Rins", position: new THREE.Vector3() },
      { nome: "Bexiga", position: new THREE.Vector3() },
      { nome: "Cérebro", position: new THREE.Vector3() },
      { nome: "Testículos", position: new THREE.Vector3() }
  ],
    orgaosF: [
      { nome: "Estômago", position: new THREE.Vector3() },
      { nome: "Intestino Delgado", position: new THREE.Vector3() },
      { nome: "Intestino Grosso e Reto", position: new THREE.Vector3() },
      { nome: "Fígado", position: new THREE.Vector3() },
      { nome: "Pâncreas", position: new THREE.Vector3() },
      { nome: "Pulmões", position: new THREE.Vector3() },
      { nome: "Coração", position: new THREE.Vector3() },
      { nome: "Rins", position: new THREE.Vector3() },
      { nome: "Bexiga", position: new THREE.Vector3() },
      { nome: "Cérebro", position: new THREE.Vector3() },
      { nome: "Ovários e Útero", position: new THREE.Vector3() },
  ],
    musculos: [
      { nome: "Quadríceps Femoral", position: new THREE.Vector3() },
      { nome: "Gastrocnêmio", position: new THREE.Vector3() },
      { nome: "Músculos Glúteos", position: new THREE.Vector3() },
      { nome: "Diafragma", position: new THREE.Vector3() },
      { nome: "Masseter", position: new THREE.Vector3() },
      { nome: "Temporal", position: new THREE.Vector3() },
      { nome: "Tríceps Braquial", position: new THREE.Vector3() },
      { nome: "Bíceps Braquial", position: new THREE.Vector3() },
      { nome: "Intercostais Externos", position: new THREE.Vector3() },
      { nome: "Reto do Abdômen", position: new THREE.Vector3() }
]
  },
  "Papagaio": {
    ossea: [
      { nome: "Órbita", position: new THREE.Vector3(0.05, 1.84, 1.04) },
      { nome: "Crânio", position: new THREE.Vector3(0.19, 1.90, 0.73) },
      { nome: "Vértebras cervicais", position: new THREE.Vector3(0.11, 0.94, 0.81) },
      { nome: "Quilha do esterno", position: new THREE.Vector3(0.17, -0.48, -0.03) },
      { nome: "Esterno", position: new THREE.Vector3(0.36, -0.15, -0.15) },
      { nome: "Úmero", position: new THREE.Vector3(0.71, 0.40, 0.09) },
      { nome: "Cúbito", position: new THREE.Vector3(0.96, 0.22, 0.21) },
      { nome: "Rádio", position: new THREE.Vector3(1.11, 0.08, 0.26) },
      { nome: "Tíbia-tarso", position: new THREE.Vector3(0.76, -0.69, -0.90) },
      { nome: "Tarso-metatarso", position: new THREE.Vector3(0.86, -1.09, -0.78) },
      { nome: "Fêmur", position: new THREE.Vector3(0.61, -0.04, -0.46) },
      { nome: "Pelve", position: new THREE.Vector3(0.34, 0.05, -0.82) },
      { nome: "Sinsacro", position: new THREE.Vector3(0.01, -0.04, -1.06) },
      { nome: "Pigóstilo", position: new THREE.Vector3(0.06, -0.56, -1.74) },
      { nome: "Vértebras caudais", position: new THREE.Vector3(0.04, -0.48, -1.48) },
      { nome: "Vértebras torácicas", position: new THREE.Vector3(0.05, 0.61, -0.08) },
      { nome: "Escápula", position: new THREE.Vector3(0.45, 0.42, 0.30) },
      { nome: "Coracoide", position: new THREE.Vector3(0.53, 0.25, -0.05) },
      { nome: "Costelas", position: new THREE.Vector3(0.36, -0.15, -0.15) }
    ],
    orgaosM: [
      { nome: "Cérebro", position: new THREE.Vector3() },
      { nome: "Pulmão", position: new THREE.Vector3() },
      { nome: "Coração", position: new THREE.Vector3() },
      { nome: "Fígado", position: new THREE.Vector3() },
      { nome: "Moela", position: new THREE.Vector3() },
      { nome: "Proventrículo", position: new THREE.Vector3() },
      { nome: "Intestino", position: new THREE.Vector3() },
      { nome: "Rins", position: new THREE.Vector3() },
      { nome: "Testículos", position: new THREE.Vector3() },
      { nome: "Pâncreas", position: new THREE.Vector3() },
      { nome: "Esôfago e Papo", position: new THREE.Vector3() },
      { nome: "Cloaca", position: new THREE.Vector3() },
      { nome: "Traqueia", position: new THREE.Vector3() },
      { nome: "Siringe", position: new THREE.Vector3() },
      { nome: "Sacos Aéreos", position: new THREE.Vector3() }
  ],
    orgaosF: [
      { nome: "Cérebro", position: new THREE.Vector3() },
      { nome: "Pulmão", position: new THREE.Vector3() },
      { nome: "Coração", position: new THREE.Vector3() },
      { nome: "Fígado", position: new THREE.Vector3() },
      { nome: "Moela", position: new THREE.Vector3() },
      { nome: "Proventrículo", position: new THREE.Vector3() },
      { nome: "Intestino", position: new THREE.Vector3() },
      { nome: "Rins", position: new THREE.Vector3() },
      { nome: "Ovário e Oviduto", position: new THREE.Vector3() },
      { nome: "Pâncreas", position: new THREE.Vector3() },
      { nome: "Esôfago e Papo", position: new THREE.Vector3() },
      { nome: "Cloaca", position: new THREE.Vector3() },
      { nome: "Traqueia", position: new THREE.Vector3() },
      { nome: "Siringe", position: new THREE.Vector3() },
      { nome: "Sacos Aéreos", position: new THREE.Vector3() }
  ],
    muscular: [
      { nome: "Pectoralis Major", position: new THREE.Vector3() }, 
      { nome: "Supracoracoideus", position: new THREE.Vector3() }, 
      { nome: "Biceps Brachii", position: new THREE.Vector3() },
      { nome: "Triceps Brachii", position: new THREE.Vector3() },
      { nome: "Flexor Carpi Ulnaris", position: new THREE.Vector3() },
      { nome: "Extensor Carpi Radialis", position: new THREE.Vector3() },
      { nome: "Deltoideus", position: new THREE.Vector3() }, 
      { nome: "Levator Scapulae", position: new THREE.Vector3() }, 
      { nome: "Splenius", position: new THREE.Vector3() }, 
      { nome: "Depressor Mandibulae", position: new THREE.Vector3() }, 
      { nome: "Gastrocnemius", position: new THREE.Vector3() }, 
      { nome: "Tibialis Anterior", position: new THREE.Vector3() },
      { nome: "Flexor Digitorum Longus", position: new THREE.Vector3() },
      { nome: "Iliofibularis", position: new THREE.Vector3() },
      { nome: "Levator Caudae", position: new THREE.Vector3() }, 
      { nome: "Depressor Caudae", position: new THREE.Vector3() },
      { nome: "Longissimus Dorsi", position: new THREE.Vector3() }
]
  },
  "Tubarão": {
    ossea: [
      { nome: "Crânio/Neurocrânio", position: new THREE.Vector3() },
      { nome: "Mandíbulas", position: new THREE.Vector3() },
      { nome: "Coluna Vertebral", position: new THREE.Vector3() },
      { nome: "Nadadeiras Peitorais", position: new THREE.Vector3() },
      { nome: "Cintura Peitoral/Escapular", position: new THREE.Vector3() },
      { nome: "Cintura Pélvica", position: new THREE.Vector3() },
      { nome: "Nadadeira Caudal", position: new THREE.Vector3() },
      { nome: "Arcos Branquiais", position: new THREE.Vector3() },
      { nome: "Nadadeira Dorsal", position: new THREE.Vector3() }
  ],
    orgaosM: [
      { nome: "Bocas e dentes", position: new THREE.Vector3() },
      { nome: "Brânquias", position: new THREE.Vector3() },
      { nome: "Coração", position: new THREE.Vector3() },
      { nome: "Fígado", position: new THREE.Vector3() },
      { nome: "Estômago", position: new THREE.Vector3() },
      { nome: "Intestino com Vávula Espiral", position: new THREE.Vector3() },
      { nome: "Glândula Retal", position: new THREE.Vector3() },
      { nome: "Rins", position: new THREE.Vector3() },
      { nome: "Espiráculos", position: new THREE.Vector3() },
      { nome: "Cláspers", position: new THREE.Vector3() },
      { nome: "Ampolas de Lorenzini", position: new THREE.Vector3() },
      { nome: "Cérebro", position: new THREE.Vector3() },
      { nome: "Sistema de linha lateral", position: new THREE.Vector3() },
      { nome: "Olhos", position: new THREE.Vector3() },
      { nome: "Narinas e Sistema Olfatório", position: new THREE.Vector3() },
      { nome: "Vesícula Biliar", position: new THREE.Vector3() },
      { nome: "Pâncreas", position: new THREE.Vector3() },
      { nome: "Baço", position: new THREE.Vector3() }
    ],
    orgaosF: [
      { nome: "Bocas e dentes", position: new THREE.Vector3() },
      { nome: "Brânquias", position: new THREE.Vector3() },
      { nome: "Coração", position: new THREE.Vector3() },
      { nome: "Fígado", position: new THREE.Vector3() },
      { nome: "Estômago", position: new THREE.Vector3() },
      { nome: "Intestino com Vávula Espiral", position: new THREE.Vector3() },
      { nome: "Glândula Retal", position: new THREE.Vector3() },
      { nome: "Rins", position: new THREE.Vector3() },
      { nome: "Espiráculos", position: new THREE.Vector3() },
      { nome: "Glândulas Nidamentais", position: new THREE.Vector3() },
      { nome: "Úteros", position: new THREE.Vector3() },
      { nome: "Ampolas de Lorenzini", position: new THREE.Vector3() },
      { nome: "Cérebro", position: new THREE.Vector3() },
      { nome: "Sistema de linha lateral", position: new THREE.Vector3() },
      { nome: "Olhos", position: new THREE.Vector3() },
      { nome: "Narinas e Sistema Olfatório", position: new THREE.Vector3() },
      { nome: "Vesícula Biliar", position: new THREE.Vector3() },
      { nome: "Pâncreas", position: new THREE.Vector3() },
      { nome: "Baço", position: new THREE.Vector3() }
    ],
    muscular: [
      { nome: "Miômeros/Miótomos", position: new THREE.Vector3() },
      { nome: "Músculos Brancos (Fibras brancas)", position: new THREE.Vector3() },
      { nome: "Músculos Vermelhos (Fibras vermelhas)", position: new THREE.Vector3() },
      { nome: "Músculos Epaxiais", position: new THREE.Vector3() },
      { nome: "Músculos Hipaxiais", position: new THREE.Vector3() },
      { nome: "Elevadores das nadadeiras", position: new THREE.Vector3() },
      { nome: "Depressores das nadadeiras", position: new THREE.Vector3() },
      { nome: "Músculos das Nadadeiras Dorsais", position: new THREE.Vector3() },
      { nome: "Músculos das Nadadeiras Caudal", position: new THREE.Vector3() },
      { nome: "Músculos das Nadadeiras Pélvicas", position: new THREE.Vector3() },
      { nome: "Adutor Mandíbular", position: new THREE.Vector3() },
      { nome: "Levator Palatoquadrado", position: new THREE.Vector3() },
      { nome: "Coracomandibular", position: new THREE.Vector3() },
      { nome: "Constritores Branquiais", position: new THREE.Vector3() },
      { nome: "Esfíncter do Espiráculo", position: new THREE.Vector3() },
      { nome: "Músculos Hipobranchiais", position: new THREE.Vector3() },
      { nome: "Músculos Lisos do Intestino", position: new THREE.Vector3() },
      { nome: "Esfíncter Cloacal", position: new THREE.Vector3() },
      { nome: "Músculos Oculomotores", position: new THREE.Vector3() }
    ],
  }
};

export const modeloIDPorAnimalECamada = {
  Cachorro: {
    ossea: 1,
    orgaos: 2,
    muscular: 3,
    epiderme: 4
  },
  Vaca: {
    epiderme: 5,
    ossea: 6,
    orgaos: 7,
    muscular: 8
  },
  Cavalo: {
    epiderme: 9,
    ossea: 10,
    orgaos: 11,
    muscular: 12
  },
  Peixe: {
    epiderme: 13,
    ossea: 14,
    orgaos: 15,
    muscular: 16
  },
  Rato: {
    epiderme: 17,
    ossea: 18,
    orgaos: 19,
    muscular: 20
  },
  Papagaio: {
    epiderme: 21,
    ossea: 22,
    orgaos: 23,
    muscular: 24
  },
  Tubarão: {
    epiderme: 25,
    ossea: 26,
    orgaos: 27,
    muscular: 28
  }
};